### ISSUE TITLE
Issue when upgrade to 2.0.1

### ISSUE THREAD

**Issue by camilonova** [caioariede/django-location-field#71]
I just upgraded the library from 1.6 and got this error:

```'Settings' object has no attribute 'LOCATION_FIELD'```

Seems is not taking the default value since I don't have any ```LOCATION_FIELD``` setting.

**Comment by caioariede** [comment]
@camilonova Could you please paste the full stack trace?

**Comment by marteinn** [comment]
@caioariede I'm experiencing the same issue, here's the stacktrace. I'm running django 1.9.12

```
AttributeError at /admin/restaurant/restaurant/1/change/
'Settings' object has no attribute 'LOCATION_FIELD'
Request Method:	GET
Request URL:	http://site.dev:8085/admin/restaurant/restaurant/1/change/
Django Version:	1.9.12
Exception Type:	AttributeError
Exception Value:	
'Settings' object has no attribute 'LOCATION_FIELD'
Exception Location:	/usr/local/lib/python2.7/site-packages/django/conf/__init__.py in __getattr__, line 56
Python Executable:	/usr/local/bin/python
Python Version:	2.7.12
Python Path:	
['/app',
 '/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/site-packages']
Server time:	Fri, 27 Jan 2017 12:41:43 +0100


Traceback:

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py" in wrapper
  541.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py" in inner
  244.             return view(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py" in change_view
  1440.         return self.changeform_view(request, object_id, form_url, extra_context)

File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  184.                     return func(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py" in changeform_view
  1367.         ModelForm = self.get_form(request, obj)

File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py" in get_form
  639.             return modelform_factory(self.model, **defaults)

File "/usr/local/lib/python2.7/site-packages/django/forms/models.py" in modelform_factory
  545.     return type(form)(class_name, (form,), form_class_attrs)

File "/usr/local/lib/python2.7/site-packages/django/forms/models.py" in __new__
  247.                                       opts.field_classes)

File "/usr/local/lib/python2.7/site-packages/django/forms/models.py" in fields_for_model
  176.             formfield = formfield_callback(f, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py" in formfield_for_dbfield
  176.         return db_field.formfield(**kwargs)

File "/usr/local/lib/python2.7/site-packages/location_field/models/base.py" in formfield
  11.             **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/db/models/fields.py" in formfield
  292.         return super(GeometryField, self).formfield(**defaults)

File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py" in formfield
  903.         return form_class(**defaults)

File "/usr/local/lib/python2.7/site-packages/location_field/forms/plain.py" in __init__
  12.                                      suffix=suffix, **kwargs)

File "/usr/local/lib/python2.7/site-packages/location_field/widgets.py" in __init__
  15.         self.options = dict(settings.LOCATION_FIELD)

File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py" in __getattr__
  56.         return getattr(self._wrapped, name)

Exception Type: AttributeError at /admin/restaurant/restaurant/1/change/
Exception Value: 'Settings' object has no attribute 'LOCATION_FIELD'
```

**Comment by marteinn** [comment]
@caioariede It seems to be like a result of the AppConfig not autoloading with the installed app.

I took a quick look at the docs and following the recommendation to add `location_field.apps.DefaultConfig` to INSTALLED_APPS solved issue. 

Is there a reason why you don't autoload DefaultConfig with the app? Like this:

File: `location_field/__init__.py`

```python
default_app_config = 'location_field.apps.DefaultConfig'
```

**Comment by caioariede** [comment]
Thank you guys, you helped a lot!

I just released 2.0.2 that contains the patch for this issue.

Looking forward to Django 1.11 and 2.0 :)

**Comment by marteinn** [comment]
@caioariede Awesome! Thanks for the quick fix! 👍

**Comment by camilonova** [comment]
Thank you

**Comment by andytwoods** [comment]
I'm having the same trouble with django-location-field==2.0.6. Copy pasting contents of \site-packages\location_field\apps.py into my settings fixed this. I am using Django > v2 though so perhaps this is an incompatibility thing.
